######################################################################
# Automatically generated by qmake (2.01a) mar. mars 29 12:36:52 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h ../client/repr.h ../client/tools.h
FORMS += gui.ui
SOURCES += gui.cpp main.cpp ../client/repr.cpp ../client/tools.cpp
